on:
  push:
    tags:
      - v*
defaults:
 run:
  working-directory: ./app_ci_cd
name: Continuous Delivery Release apk
jobs:
  build:
    name: Build APk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          # lutter-version: '3.0.5'
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      #- run: flutter build apk -t lib/main.dart --split-per-abi
      - run: ls build/
        # working-directory: ./app_ci_cd
      - name: Release APK
        uses: ncipollo/release-action@v1
        with:
          # artifacts: "build/app/outputs/apk/debug/*.apk"
                      # build\app\outputs\flutter-apk\
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{ secrets.cidi_flutter}}
