on:
  push:
    tags:
      - v*
defaults:
 run:
  working-directory: ./app_ci_cd
name: Continuous Delivery Release apk
jobs:
  build:
    name: Build APk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          # lutter-version: '3.0.5'
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - name: Build APK
        run: flutter build apk -t lib/main.dart --split-per-abi
      - run: ls
      - run: ls build
      - run: ls build/app
      - run: ls build/app/outputs
      - run: ls build/app/outputs/apk
      - run: ls build/app/outputs/apk/release
      - name: Release apk
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.cidi_flutter}}
      # - run: flutter build apk --split-per-abi
      # - run: ls build/
      # - name: Release APK
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "build/app/outputs/flutter-apk/*.apk"
      #     token: ${{ secrets.cidi_flutter}}
      # artifacts: "build/app/outputs/apk/release/*.apk"
      # - run: flutter build apk --split-per-abi
      # - run: ls build/
      # - name: Release APK
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "build/app/outputs/flutter-apk/*.apk"
      #     token: ${{ secrets.cidi_flutter}}