on:
  push:
    tags:
      - v*
  workflow_dispatch:
defaults:
 run:
  working-directory: ./app_ci_cd
name: Continuous Delivery Release apk
jobs:
  build:
    name: Build APk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '12'
      - uses: subosito/flutter-action@v2
        with:
          # lutter-version: '3.0.5'
          channel: 'stable'
      - run: flutter --version
      - name: Pub Get Packages
      - run: flutter pub get
      - run: flutter test
        run: flutter build apk -t lib/main.dart --split-per-abi
      - name: Release apk
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
      # - run: flutter build apk --split-per-abi
      # - run: ls build/
      # - name: Release APK
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "build/app/outputs/flutter-apk/*.apk"
      #     token: ${{ secrets.cidi_flutter}}